version: "3.9"
services:
  web-test:
    build: .
    ports:
      - "8080:8080"
  prometheus:
    image: "prom/prometheus"
    ports:
      - "9090:9090"
    volumes:
      - "./_test/prometheus.yml:/etc/prometheus/prometheus.yml"